This PR fixes and vastly improves the tests, if they don't pass changes will be much easier
tijlleenders/ZinZen-scheduler pull request #15
Opened 2022-05-30 14:57 UTC by sokorototo

Branch pollution is real, so whenever we finish a PR we delete the branch, this ensures all branches are as close to `main` as possible to prevent excess merge conflicts

2022-05-30 14:58 UTC, sokorototo commented
Hmm I don't have write access? Why? We are only two people after all

2022-05-30 15:58 UTC, tijlleenders commented
> Hmm I don't have write access? Why? We are only two people after all. Or is it that I just need an approving review first

Yeah I communicated this by chat. Main is protected now. We'll integrate PRs that close issues, like any project. Thisvsetsbup the project for better collaboration.

2022-05-30 16:17 UTC, tijlleenders requested changes
Onnour way!

test/goals.json date and times are not conform test case.

Also some "finish" instances that need renaming to deadline.

2022-05-30 16:17 UTC, tijlleenders commented on test/goals.json
> +    "deadline": "June 2, 2022 18:00:00"
I understand the format change but the date and time don't have to be changed.

2022-05-30 16:17 UTC, tijlleenders commented on ts/api.ts
>  	finish: DateTime,
Shoukd be deadline

2022-05-30 16:20 UTC, tijlleenders commented
Good to see the test passing!

The asserts still need to be added to make the test fail.

2022-05-31 12:16 UTC, sokorototo commented
Asserts are already in place

2022-05-31 15:41 UTC, tijlleenders commented
> Asserts are already in place

Where?
I only see one assert in the test:
![image](https://user-images.githubusercontent.com/44887755/171213913-7269c863-0a21-4fdd-b7f2-3ce790a0f2d3.png)


What I need is assert the expected outcome:
Three tasks scheduled according to the expectation defined in the issue #3 

I'll write it here too:
Goal 1 => One task from 11-12
Goal 2 => One task from 10-11
Goal 3 => One task from 13-14

2022-06-03 08:56 UTC, tijlleenders approved these changes
Just merging this to restart implementation of preprocessor and scheduler logic.

2022-06-03 08:56 UTC, merged