create simple edge case with 3 goals
tijlleenders/ZinZen-scheduler pull request #78
Opened 2022-09-14 11:32 UTC by JacobJax

Created a simple schedule edge case with `input.json` and `output.json` in the `basic-test-1` folder.
Help me confirm that the output is correct.

2022-09-14 11:53 UTC, egithinji requested changes
Great first test! Just one observation: I think two tasks mistakenly have task id 2.

2022-09-14 15:24 UTC, tijlleenders requested changes
Are you sure the logic of the test case is OK?
Nothing has flexibility of 1, the swimming seems to have the greatest flexibility so gets scheduled first, 11-13 is the slot with the least overlap - so I expect that to be the times for swimming...

2022-09-15 07:30 UTC, egithinji approved these changes

2022-09-16 07:38 UTC, tijlleenders approved these changes
Eric already approved it so it can be merged.

2022-09-16 07:39 UTC, merged